version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    ports:
      - "9000:9000"
      - "8123:8123"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"

  stats-service:
    build: ./stats-service
    depends_on:
      - kafka
      - clickhouse

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - stats-service
